In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

In [ ]:
df = pd.read_csv('/content/house_prices.csv')
df.head()

,sqft_living,bedrooms,bathrooms,floors,house_age,dist_to_city_km,quality_score,price
0,959,4,2.0,2.0,10,13.97,6,256153
1,3173,4,2.6,2.0,9,1.40,4,602494
2,2017,1,1.9,1.0,71,0.24,9,403973
3,818,5,3.7,1.5,45,13.07,3,208514
4,2036,3,2.3,2.0,57,1.90,5,396980

In [ ]:
df.describe()

,sqft_living,bedrooms,bathrooms,floors,house_age,dist_to_city_km,quality_score,price
count,1000.000000,1000.000000,988.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,1872.225000,3.368000,2.528745,1.621500,19.530000,8.020810,6.581000,4.081768e+05
std,721.658094,1.189955,0.963300,0.613077,18.964882,7.635918,2.240638,1.518990e+05
min,450.000000,1.000000,1.000000,1.000000,0.000000,0.200000,3.000000,8.956100e+04
25%,1362.000000,3.000000,1.800000,1.000000,6.000000,2.327500,5.000000,3.257180e+05
50%,1873.500000,3.000000,2.500000,1.500000,13.000000,5.690000,7.000000,4.020970e+05
75%,2358.000000,4.000000,3.100000,2.000000,27.000000,11.495000,9.000000,4.792382e+05
max,3927.000000,6.000000,5.000000,3.000000,100.000000,46.160000,10.000000,2.558280e+06

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.isnull().sum()

sqft_living         0
bedrooms            0
bathrooms          12
floors              0
house_age           0
dist_to_city_km     0
quality_score       0
price               0
dtype: int64

In [ ]:
df['bathrooms'] = df['bathrooms'].fillna(df['bathrooms'].median())
df.isnull().sum()

sqft_living        0
bedrooms           0
bathrooms          0
floors             0
house_age          0
dist_to_city_km    0
quality_score      0
price              0
dtype: int64

In [ ]:
q1 = df['price'].quantile(0.25)
q3 = df['price'].quantile(0.75)
iqr = q3 - q1
upper = q3 + 3 * iqr
df = df[df['price']<=upper]
df.shape

(997, 8)

In [ ]:
x = df.drop(columns = 'price')
y = df['price']

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(x)
x_std = scaler.transform(x)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 2)

In [ ]:
print(x.shape, x_train.shape, x_test.shape)

(997, 7) (797, 7) (200, 7)

In [ ]:
cf = RandomForestRegressor(n_estimators=200, max_depth = 10,random_state = 2 )

In [ ]:
cf.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, random_state=2)

In [ ]:
x_train_pred = cf.predict(x_train)

In [ ]:
x_train_r2 = r2_score(y_train,x_train_pred)

In [ ]:
print(x_train_r2)

0.9914703176063271

In [ ]:
x_test_pred = cf.predict(x_test)
x_test_r2 = r2_score(y_test, x_test_pred)

In [ ]:
print(x_test_r2)

0.9443159384283488

In [ ]:
data = [1461,	4,	3.3,	1,	34,	15.69,	3]
print(data)

[1461, 4, 3.3, 1, 34, 15.69, 3]

In [ ]:
data_np = np.asanyarray(data)
print(data_np)

[1.461e+03 4.000e+00 3.300e+00 1.000e+00 3.400e+01 1.569e+01 3.000e+00]

In [ ]:
data_reshape = data_np.reshape(1,-1)

In [ ]:
input_std = scaler.transform(data_reshape)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
print(input_std)

[[-0.56989897  0.5313711   0.80530058 -1.01344286  0.76243852  1.00400387
  -1.60376145]]

In [ ]:
pred = cf.predict(input_std)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [ ]:
print(pred)

[190315.49210354]